---
# Source: redis/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ext-redis
  labels:
    app: redis
    chart: redis-3.7.6
    release: "ext"
    heritage: "Tiller"
type: Opaque
data:
  redis-password: "cmVkaXM="
---
# Source: redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: ext-redis-master
  labels:
    app: redis
    chart: redis-3.7.6
    release: "ext"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "ext"
    role: master

---
# Source: redis/templates/redis-master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ext-redis-master
  labels:
    app: redis
    chart: redis-3.7.6
    release: "ext"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      release: "ext"
      chart: redis-3.7.6
      role: master
      app: redis
  serviceName: "redis-master"
  template:
    metadata:
      labels:
        release: "ext"
        chart: redis-3.7.6
        role: master
        app: redis
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: "default"
      containers:
      - name: ext-redis
        image: "docker.io/bitnami/redis:4.0.11-debian-9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ext-redis
              key: redis-password
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - redis-cli
            - ping
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - redis-cli
            - ping
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app: "redis"
        chart: redis-3.7.6
        component: "master"
        release: "ext"
        heritage: "Tiller"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "8Gi"
  updateStrategy:
    type: OnDelete

---
# Source: redis/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ext-bootstrap-redis
  labels:
    app: redis
    chart: redis-3.7.6
    release: "ext-bootstrap"
    heritage: "Tiller"
type: Opaque
data:
  redis-password: "cmVkaXM="
---
# Source: redis/templates/redis-master-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: ext-bootstrap-redis-master
  labels:
    app: redis
    chart: redis-3.7.6
    release: "ext-bootstrap"
    heritage: "Tiller"
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: redis
  selector:
    app: redis
    release: "ext-bootstrap"
    role: master

---
# Source: redis/templates/redis-master-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ext-bootstrap-redis-master
  labels:
    app: redis
    chart: redis-3.7.6
    release: "ext-bootstrap"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      release: "ext-bootstrap"
      chart: redis-3.7.6
      role: master
      app: redis
  serviceName: "redis-master"
  template:
    metadata:
      labels:
        release: "ext-bootstrap"
        chart: redis-3.7.6
        role: master
        app: redis
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      serviceAccountName: "default"
      containers:
      - name: ext-bootstrap-redis
        image: "docker.io/bitnami/redis:4.0.11-debian-9"
        imagePullPolicy: "IfNotPresent"
        env:
        - name: REDIS_REPLICATION_MODE
          value: master
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ext-bootstrap-redis
              key: redis-password
        ports:
        - name: redis
          containerPort: 6379
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - redis-cli
            - ping
        readinessProbe:
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
          exec:
            command:
            - redis-cli
            - ping
        volumeMounts:
        - name: redis-data
          mountPath: /bitnami/redis/data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
      labels:
        app: "redis"
        chart: redis-3.7.6
        component: "master"
        release: "ext-bootstrap"
        heritage: "Tiller"
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "8Gi"
  updateStrategy:
    type: OnDelete

