schema: "1"
pipeline:
  application: <APP_NAME>
  name: Deploy to Prod
  template:
    source: spinnaker://deployToProd
  variables:
    canary:
      pipelineId: "<TEST_DEPLOY_PIPELINE_ID>"
      cluster: "<APP_NAME>-dev"
      account: "my-k8s-account"
      namespace: "default"
    prod:
      cluster: "<APP_NAME>-prod"
      account: "my-k8s-account"
      namespace: "default"
      probePath: "/actuator/health"
      loadBalancers:
      - <APP_NAME>-prod
    canaryConfig:
      beginInterval: 1
      analysisInterval: 5
      duration: 5
      configId: "<CANARY_CONFIG_ID>"
      metricsAccount: my-google-account
      storageAccount: my-google-account
configuration:
  inherit: [ "concurrentExecutions", "triggers" ]
