schema: "1"
id: deployToTest
metadata:
  name: Deploy an image from trigger to Test Env
  description: Deploy an image from trigger to Test Env
  owner: pipelineservice@ea.anz.com
  scopes:
    - global
protect: false
source: spinnaker://common-modules
variables:
- name: image
  type: Object
- name: cluster
  type: Object
configuration:
  concurrentExecutions:
    limitConcurrent: true
    parallel: true
  triggers:
  - type: docker
    enabled: true
    account: "{{ image.account }}"
    organization: "{{ image.organization }}"
    registry: "{{ image.registry }}"
    repository: "{{ image.organization }}/{{ image.name }}"
stages:
- id: deploy
  type: deploy
  name: "Deploy to {{ cluster.stack }}"
  config:
    clusters: |
      {% if cluster %}
      - {% module  deployCluster
          account=cluster.account,
          namespace=cluster.namespace,
          size=cluster.size,
          port=cluster.port,
          loadBalancers=cluster.loadBalancers,
          strategy="highlander",
          stack=cluster.stack,
          probePath=cluster.probePath,
          imageAccount=image.account,
          imageOrg=image.organization,
          imageRegistry=image.registry,
          imageName=image.name%}
      {% endif %}
