---
apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>-dev
  namespace: default
  labels:
    app: <APP_NAME>
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-<APP_NAME>-dev: "true"
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: <APP_NAME>-prod
  namespace: default
  labels:
    app: <APP_NAME>
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    load-balancer-<APP_NAME>-prod: "true"
  sessionAffinity: None
  type: ClusterIP
