apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: helloworld-dev
    namespace: default
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      load-balancer-helloworld-dev: "true"
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    name: helloworld-prod
    namespace: default
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      load-balancer-helloworld-prod: "true"
    sessionAffinity: None
    type: ClusterIP
kind: List
