steps:
- name: 'hashicorp/terraform:light'
  dir: 'spinnaker'
  args:
  - 'init'
- name: 'hashicorp/terraform:light'
  dir: 'spinnaker'
  args: ['plan', '-out', 'spinnaker.plan','-var', 'project=$PROJECT_ID', -var, 'gcs_location="australia-southeast1"', '-var', 'gcs_class_storage="REGIONAL"']
- name: 'hashicorp/terraform:light'
  dir: 'spinnaker'
  args: ['apply', '-auto-approve', 'spinnaker.plan']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'sh'
  dir: 'spinnaker'
  args:
    - -c
    - |
      pwd
      ls -al
- name: 'gcr.io/cloud-builders/kubectl'
  dir: 'spinnaker'
  args: 
  - 'apply'
  - '-f'
  - 'init-spinnaker-manifest.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ea-base-gke'