steps:
- name: 'hashicorp/terraform:light'
  args: ['init']
  dir: 'spinnaker'
- name: 'hashicorp/terraform:light'
  args: ['plan']
  dir: 'spinnaker'
- name: 'hashicorp/terraform:light'
  args: ['apply']
  dir: 'spinnaker'