steps:
- name: 'hashicorp/terraform:light'
  args: ['init']
  dir: 'spinnaker'
- name: 'hashicorp/terraform:light'
  args: ['plan', '-out', 'spinnaker.plan','-var', 'project=$PROJECT_ID', -var, 'gcs_location="australia-southeast1"', '-var', 'gcs_class_storage="REGIONAL"']
  dir: 'spinnaker'
- name: 'hashicorp/terraform:light'
  args: ['apply', '-auto-approve', 'spinnaker.plan']
  dir: 'spinnaker'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'init-spinnaker-manifest.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=ea-base-gke'