substitutions:
    _CLOUDSDK_COMPUTE_ZONE: australia-southeast1-a
    _CLOUDSDK_CONTAINER_CLUSTER: ea-base-gke
steps:
- name: 'hashicorp/terraform:light'
  dir: 'spinnaker'
  args:
  - 'init'
- name: 'hashicorp/terraform:light'
  dir: 'spinnaker'
  args: ['plan', '-out', 'spinnaker.plan','-var', 'project=$PROJECT_ID', -var, 'gcs_location="australia-southeast1"', '-var', 'gcs_class_storage="REGIONAL"']
- name: 'hashicorp/terraform:light'
  dir: 'spinnaker'
  args: ['apply', '-auto-approve', 'spinnaker.plan']
- name: 'gcr.io/cloud-builders/kubectl'
  dir: 'spinnaker'
  args:
  - 'apply'
  - '-f'
  - 'init-spinnaker-manifest.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
# Generate a kubeconfig file for the given GKE cluster to be used by HAL
- name: 'gcr.io/cloud-builders/gcloud'
  env:
    - 'KUBECONFIG=/kube/config'
  args:
   - 'container'
   - 'clusters'
   - 'get-credentials'
   - '${_CLOUDSDK_CONTAINER_CLUSTER}'
   - '--zone'
   - '${_CLOUDSDK_COMPUTE_ZONE}'
  volumes:
    - name: 'kube'
      path: /kube
# - name: 'gcr.io/spinnaker-marketplace/halyard:stable'
#   env:
#     - 'KUBECONFIG=/kube/config'
#   dir: 'spinnaker'
#   args:
#     - 'config'
#     - 'provider'
#     - 'kubernetes'
#     - 'enable'
#   volumes:
#     - name: 'kube'
#       path: /kube
- name: 'hashicorp/terraform:light'
  dir: 'spinnaker'
  args: ['destroy', '-auto-approve']