steps:
- name: 'hashicorp/terraform:light'
  args: ['init']
  dir: 'spinnaker'
- name: 'hashicorp/terraform:light'
  args: ['plan', '-var', 'project=$PROJECT_ID', -var, 'gcs_location="australia-southeast1"', '-var', 'gcs_class_storage="REGIONAL"']
  dir: 'spinnaker'
- name: 'hashicorp/terraform:light'
  args: ['apply', '-var', 'project=$PROJECT_ID', -var, 'gcs_location="australia-southeast1"', '-var', 'gcs_class_storage="REGIONAL"']
  dir: 'spinnaker'